// RFC 4180 reader used against the generated bytes, not only the input model.
export function parseJobberCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [], cell = "", quoted = false;
  for (let i = 0; i < csv.length; i++) {
    const c = csv[i]!;
    if (c === '"') {
      if (quoted && csv[i + 1] === '"') { cell += '"'; i++; }
      else quoted = !quoted;
    } else if (c === "," && !quoted) { row.push(cell); cell = ""; }
    else if ((c === "\r" || c === "\n") && !quoted) {
      if (c === "\r" && csv[i + 1] === "\n") i++;
      row.push(cell); rows.push(row); row = []; cell = "";
    } else cell += c;
  }
  if (quoted) throw new Error("Unclosed CSV quotation.");
  if (row.length || cell) { row.push(cell); rows.push(row); }
  return rows;
}

export function validateJobberCsv(csv: string, expectedHeaders: string[], expectedTotal: number, representedTotal: number) {
  const errors: string[] = [];
  if (Buffer.from(csv, "utf8").toString("utf8") !== csv) errors.push("Invalid UTF-8 text.");
  let rows: string[][];
  try { rows = parseJobberCsv(csv); } catch { return ["Invalid CSV escaping."]; }
  if (rows.length !== 2) errors.push("Expected one header and one quote row.");
  if (JSON.stringify(rows[0]) !== JSON.stringify(expectedHeaders) || expectedHeaders.length !== 119)
    errors.push("Headers do not match the official 119-column sample.");
  const values = rows[1] ?? [];
  if (values.length !== expectedHeaders.length) errors.push("Incorrect data column count.");
  const get = (name: string) => values[expectedHeaders.indexOf(name)] ?? "";
  values.forEach((v, i) => {
    if (/\[object Object\]|^(?:undefined|NaN|null)$/i.test(v)) errors.push(`Invalid value in column ${i + 1}.`);
    if (expectedHeaders[i]?.endsWith("(True/False)") && v && v !== "TRUE" && v !== "FALSE")
      errors.push(`Invalid boolean in column ${i + 1}.`);
  });
  if (!["Draft", "Awaiting Response"].includes(get("Quote Status (Draft/Awaiting Response/Approved)")))
    errors.push("Invalid quote status.");
  const method = get("Tax Method (Inclusive/Exclusive)");
  if (method && !["Inclusive", "Exclusive"].includes(method)) errors.push("Invalid tax method.");
  let count = 0;
  for (let i = 1; i <= 10; i++) {
    const prefix = `Line Item ${i} `;
    const category = get(prefix + "Category (Service/Product)");
    if (!category) continue;
    count++;
    if (!["Service", "Product"].includes(category)) errors.push("Invalid line category.");
    if (!get(prefix + "Name").trim()) errors.push("Missing line name.");
    for (const [suffix, positive] of [["Quantity", true], ["UNIT Price", false], ["UNIT Cost", false]] as const) {
      const v = get(prefix + suffix);
      if (suffix === "UNIT Cost" && !v) continue;
      if (!/^\d+(?:\.\d+)?$/.test(v) || (positive && Number(v) <= 0))
        errors.push(`Invalid line ${i} ${suffix}.`);
    }
  }
  if (!count) errors.push("At least one service line is required.");
  if (Math.round(expectedTotal * 100) !== Math.round(representedTotal * 100))
    errors.push("Export total differs from the saved final selling price.");
  return errors;
}
